# name: Osaka Masjid

# on:
#   push:
#     branches:
#       - main  # deploy whenever code is pushed to main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Deploy to server via SSH
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             cd /www/wwwroot/osakamasjid.org
#             export PATH=$PATH:/www/server/nvm/versions/node/v20.17.0/bin

#             # Stop and remove existing PM2 process
#             pm2 stop osaka-mosque || true
#             pm2 delete osaka-mosque || true
#             pm2 save

#             # Clean old build and dependencies
#             rm -rf node_modules/ .next/

#             # Pull latest code and install dependencies
#             git stash
#             git pull origin main
#             npm install

#             # Build and restart app
#             npm run build
#             npm run pm2:start

#             # Save PM2 state
#             pm2 save
